import React, { useMemo } from 'react';
import {
    AreaChart, Area, LineChart, Line, BarChart, Bar,
    XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
    ReferenceLine, Cell
} from 'recharts';
import { AggregateResult } from '../../model';
import MetricEvidenceBadge from '../ui/MetricEvidenceBadge';
import { getMetricEvidence } from '../../data/metricEvidence';

interface SolvencyScorecardProps {
    data: AggregateResult[];
}

export const SolvencyScorecard: React.FC<SolvencyScorecardProps> = ({ data }) => {
    if (!data || data.length === 0) return <div>No data available</div>;

    const formattedData = useMemo(() => data.map(d => ({
        t: d.t,
        underwaterCount: d.underwaterCount.mean,
        totalNodes: d.providers.mean,
        costPerGB: d.costPerCapacity.mean,
        revenuePerGB: d.revenuePerCapacity.mean,
        joinCount: d.joinCount.mean,
        isLocked: d.entryBarrierActive.mean > 0.5 // If barrier was active in >50% of sims
    })), [data]);

    return (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 p-4">
            {/* 1. Network Distress Levels (Underwater Nodes) */}
            <div className="bg-slate-900 border border-slate-700 rounded-lg p-4 shadow-sm">
                <div className="flex items-center justify-between gap-3 mb-2">
                    <h3 className="text-lg font-semibold text-slate-100">Network Distress Levels</h3>
                    <MetricEvidenceBadge evidence={getMetricEvidence('diagnostic_underwater_count')} variant="icon" />
                </div>
                <p className="text-xs text-slate-400 mb-4">
                    Nodes operating at a loss for consecutive weeks ("Underwater").
                    <br />High distress triggers panic churn.
                </p>
                <div className="h-64">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={formattedData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                            <XAxis dataKey="t" stroke="#94a3b8" />
                            <YAxis stroke="#94a3b8" />
                            <Tooltip
                                contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f1f5f9' }}
                                itemStyle={{ color: '#f1f5f9' }}
                            />
                            <Legend />
                            <Area
                                type="monotone"
                                dataKey="underwaterCount"
                                name="Underwater Nodes"
                                stackId="1"
                                stroke="#ef4444"
                                fill="#ef4444"
                                fillOpacity={0.6}
                            />
                            <Area
                                type="monotone"
                                dataKey="totalNodes"
                                name="Healthy Nodes" // Actually Total in stack, but visuals...
                            // Stacked area is tricky if we want Underwater subset of Total. 
                            // Better: Underwater vs (Total - Underwater).
                            // But data has Total. Let's do a composed visual or just Underwater area.
                            />
                        </AreaChart>
                    </ResponsiveContainer>
                </div>
            </div>

            {/* 2. Capital Efficiency (The Gauntlet) */}
            <div className="bg-slate-900 border border-slate-700 rounded-lg p-4 shadow-sm">
                <div className="flex items-center justify-between gap-3 mb-2">
                    <h3 className="text-lg font-semibold text-slate-100">Capital Efficiency (The Gauntlet)</h3>
                    <MetricEvidenceBadge evidence={getMetricEvidence('diagnostic_cost_vs_revenue')} variant="icon" />
                </div>
                <p className="text-xs text-slate-400 mb-4">
                    Cost to incentivize 1GB vs Revenue generated by 1GB.
                    <br />Gap = Subsidy reliability. Cross = Self-sustainability.
                </p>
                <div className="h-64">
                    <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={formattedData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                            <XAxis dataKey="t" stroke="#94a3b8" />
                            <YAxis stroke="#94a3b8" />
                            <Tooltip
                                contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f1f5f9' }}
                                formatter={(value: number) => {
                                    if (value === 0) return ['$0.00', ''];
                                    if (value < 0.0001) return [`$${value.toExponential(2)}`, ''];
                                    return [`$${value.toFixed(6)}`, ''];
                                }}
                            />
                            <Legend />
                            <Line
                                type="monotone"
                                dataKey="costPerGB"
                                name="Incentive Cost / GB"
                                stroke="#f59e0b"
                                strokeWidth={2}
                                dot={false}
                            />
                            <Line
                                type="monotone"
                                dataKey="revenuePerGB"
                                name="Revenue / GB"
                                stroke="#10b981"
                                strokeWidth={2}
                                dot={false}
                            />
                        </LineChart>
                    </ResponsiveContainer>
                </div>
            </div>

            {/* 3. Net Network Growth (Trap Door / Hysteresis) */}
            <div className="col-span-1 lg:col-span-2 bg-slate-900 border border-slate-700 rounded-lg p-4 shadow-sm">
                <div className="flex items-center justify-between gap-3 mb-2">
                    <h3 className="text-lg font-semibold text-slate-100">Network Growth & Trap Door</h3>
                    <MetricEvidenceBadge evidence={getMetricEvidence('diagnostic_join_flow')} variant="icon" />
                </div>
                <p className="text-xs text-slate-400 mb-4">
                    New nodes joining per week.
                    <br /><span className="text-slate-500 font-bold">Grey bars</span> indicate growth prevented by Entry Barriers (Projected Profit &lt; CAPEX).
                </p>
                <div className="h-64 relative">
                    {(() => {
                        const isFullyLocked = formattedData.every(d => d.joinCount === 0);
                        const last5 = formattedData.slice(-5);
                        const isStalled = !isFullyLocked && last5.length > 0 && last5.every(d => d.joinCount === 0);

                        if (isFullyLocked || isStalled) {
                            return (
                                <div className="absolute inset-0 z-10 flex items-center justify-center pointer-events-none">
                                    <div className="bg-slate-900/90 border border-slate-700 p-4 rounded-xl text-center shadow-2xl backdrop-blur-sm">
                                        <div className="text-3xl mb-2">⛔</div>
                                        <h4 className="text-rose-500 font-bold text-lg">{isFullyLocked ? "TRAP DOOR CLOSED" : "GROWTH STALLED"}</h4>
                                        <p className="text-slate-400 text-xs mt-1">
                                            {isFullyLocked ? "Zero Growth." : "Network growth has halted."} Profitability is below Entry Barrier.
                                            <br />Price must rise or HW costs must fall.
                                        </p>
                                    </div>
                                </div>
                            );
                        }
                        return null;
                    })()}
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={formattedData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                            <XAxis dataKey="t" stroke="#94a3b8" />
                            <YAxis stroke="#94a3b8" />
                            <Tooltip
                                cursor={{ fill: 'rgba(255,255,255,0.05)' }}
                                content={({ active, payload }) => {
                                    if (active && payload && payload.length) {
                                        const data = payload[0].payload;
                                        const isLocked = data.isLocked && data.joinCount === 0;
                                        return (
                                            <div className="bg-slate-800 border border-slate-700 p-2 rounded shadow-lg text-xs text-slate-200">
                                                <p className="font-bold">Week {data.t}</p>
                                                <p>New Joiners: {data.joinCount.toFixed(0)}</p>
                                                {isLocked && (
                                                    <p className="text-gray-400 mt-1 italic border-t border-slate-600 pt-1">
                                                        🔒 Locked by Entry Barrier
                                                    </p>
                                                )}
                                            </div>
                                        );
                                    }
                                    return null;
                                }}
                            />
                            <Legend />
                            <Bar dataKey="joinCount" name="New Joiners">
                                {formattedData.map((entry, index) => (
                                    <Cell
                                        key={`cell-${index}`}
                                        fill={entry.joinCount === 0 && entry.isLocked ? '#475569' : '#3b82f6'} // Grey if locked, Blue if growing
                                    />
                                ))}
                            </Bar>
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            </div>
        </div>
    );
};
